### ISSUE TITLE
Support adding multiple users in a single message (Use NLP parsing per sentence, not on an entire message)

### ISSUE THREAD

**Issue by jakebolam** [all-contributors/app#100]
**Is your feature request related to a problem? Please describe.**
It would be great to have a way to bulk add users in a single request.

**Describe the solution you'd like**
Implementing per sentence parsing instead of per-message will allow us to do this. It will also help the NLP to be more effective in determining intentions. 

**Describe alternatives you've considered**

**Additional context**
Case of a user adding lots of users: https://github.com/zeroDevs/coding_challenge-13/pull/161

Broken case on message too big:
https://github.com/zeroDevs/coding_challenge-13/issues/132#issuecomment-457773736
<img width="826" alt="screen shot 2019-01-25 at 6 48 53 pm" src="https://user-images.githubusercontent.com/3534236/51778875-1b9ce980-20d2-11e9-9a4a-0137156ec9cd.png">

Case of not working:
See https://github.com/freecodecamp-ibadan/freecodecamp-ibadan/issues/4
> `@all-contributors please add @stevoo24 for code,content`
<img width="783" alt="screen shot 2019-02-10 at 11 30 04 am" src="https://user-images.githubusercontent.com/3534236/52539888-51271100-2d27-11e9-9824-5b2e35a26fba.png">

**Comment by jakebolam** [comment]
PR in progress: https://github.com/all-contributors/all-contributors-bot/pull/127

**Comment by noncash15** [comment]
#127
