### ISSUE TITLE
On first install, remove need to create README.md file

### ISSUE THREAD

**Issue by jakebolam** [all-contributors/app#105]
**Is your feature request related to a problem? Please describe.**
On the first install, let's remove the need to create a `README.md` file as documented in the [happy path install](https://all-contributors.js.org/docs/bot/installation)

**Describe the solution you'd like**
Auto create the file

**Additional context**
<img width="787" alt="screen shot 2019-01-26 at 2 27 29 pm" src="https://user-images.githubusercontent.com/3534236/51791793-a6cfbb00-2176-11e9-8187-e604166bf896.png">

May need to use the https://octokit.github.io/rest.js/#api-Repos-createFile API in the `Repository` class

**Comment by Berkmann18** [comment]
I'll have a look at that.
