### ISSUE TITLE
 avatarBlock is not defined in fileContentModifierFunction, line 58

### ISSUE THREAD

**Issue by jakebolam** [all-contributors/app#140]
**Describe the bug**
Sentry issue: https://sentry.io/all-contributors/github-bot/issues/881644816/

Affecting: https://github.com/freecodecamp-ibadan/freecodecamp-ibadan/issues/4

## Reason
For some reason the bot was crashing trying to find the users avatar.

<img width="950" alt="Screen Shot 2019-12-01 at 12 12 23 PM" src="https://user-images.githubusercontent.com/3534236/69917448-41062c80-1434-11ea-9941-d56be2e0d930.png">

<img width="1300" alt="Screen Shot 2019-12-01 at 12 12 03 PM" src="https://user-images.githubusercontent.com/3534236/69917451-45324a00-1434-11ea-913e-9887b052735b.png">

**Comment by tenshiAMD** [comment]
@jakebolam is this still relevant today? Have you checked this using the latest version? Please check and let us know if this still occurs. Closing this for now. Thanks! 🎉
