### ISSUE TITLE
stats worker fails when on probot v9

### ISSUE THREAD

**Issue by jakebolam** [all-contributors/app#178]
**Describe the bug**
With the introduction of probot v9, the stats worker started failing.

This has been fixed by rolling back to probot v8 https://github.com/all-contributors/all-contributors-bot/commit/363a206118a436ae2076f9f2f690ed5572545267

**To Reproduce**
1. Upgrade to probot 9.0.2
2. Run the stats worker in production (needs a big data set)
3. See error: object.defineProperty cannot be called on non-object inside octokit, restjs paginate

**Expected behavior**
Stats worker works

**Screenshots**
![Screen Shot 2019-03-22 at 2 41 02 PM](https://user-images.githubusercontent.com/3534236/54845730-8ae92100-4cb0-11e9-9d22-e89ad0cc3088.png)

**Additional context**
Thundral montioring shows no network errors etc prior to the crash:
https://console.thundra.io/functions/all-contributors-bot-prod-statsWorker/default/us-east-1/NODE/invocations/9aaa7e83-0a34-4ade-818e-25eb7f3c4f83/trace-chart

Interesting probot v9 requests seem stagered:
![Screen Shot 2019-03-22 at 2 50 34 PM](https://user-images.githubusercontent.com/3534236/54846284-de0fa380-4cb1-11e9-92ed-94fba5e41fb0.png)

Interesting probot v8 requests are running in parallel:
![Screen Shot 2019-03-22 at 2 53 40 PM](https://user-images.githubusercontent.com/3534236/54846482-5a09eb80-4cb2-11e9-99c6-c5d3aec2a607.png)

**Comment by jakebolam** [comment]
FYI @gr2m, unsure why this is the case

**Comment by jakebolam** [comment]
@gr2m added more info from APM, possible issue in pagination missing an await?
Sourec code bot side triggering this : https://github.com/all-contributors/all-contributors-bot/blob/master/src/tasks/stats/serverless-stats-worker.js

**Comment by gr2m** [comment]
I probably introduced the [throttle plugin](https://github.com/octokit/plugin-throttling.js) after Probot v8 beta 1. We implemented the recommend [best practises for integrators](https://developer.github.com/v3/guides/best-practices-for-integrators/), but maybe we overdid it, I don’t think there is a reason not to send HEAD/GET requests in parallel, I’ll have a look.

I’d strongly recommend against using beta v1. I’d recommend to disable the stats endpoint altogether and make a custom script which just loads the stats. It’s fairly simple to do
