### ISSUE TITLE
add Multiple Authors for same type of contributions

### ISSUE THREAD

**Issue by cstayyab** [all-contributors/app#210]
**Describe the bug**
It two users are mentions for same type of contribution when a pull request is co-authored by two or more people then only one user is being added

**To Reproduce**
1. Go to 'A pull request which have been co-authored by two or more people'
2. Create a new comment mentioning two users for same contribution as created [here](https://github.com/team5star/HighFive/pull/6#issuecomment-497941113) 

**Expected behavior**
Add both users for same type of contributions (code in this case) 

**Current Behaviour**
Only one user that was mentioned first is added

**Screenshot**
[Screenshot of comment](https://imgur.com/uD24DQa)

**Additional context**
This is required when two users have Co-Authored a pull request. You can read more about them ( Pull request with multiple authors )  [here](https://help.github.com/en/articles/creating-a-commit-with-multiple-authors)

**Comment by jakebolam** [comment]
Thanks for the report @cstayyab.

I've started a PR trying to address this problem (https://github.com/all-contributors/all-contributors-bot/pull/127), but I'm currently swamped. 

PRs welcome if you can get this over the line.

**Comment by tenshiAMD** [comment]
PR https://github.com/all-contributors/app/pull/127 is almost done. Closing this one for now.
