### ISSUE TITLE
Acknowledge multiple contributors in a single comment

### ISSUE THREAD

**Issue by zeke** [all-contributors/app#241]
👋 First off, I just want to say this project is really awesome!

I just set it up on https://github.com/repo-sync/repo-sync/pull/8 and I can't believe It Just Works™! I also guessed at the formatting for my comment `@all-contributors please add @wei for design and code and docs` and that worked as well. That [compromise](https://ghub.io/compromise) NLP tool looks really handy too.

Anyway, on to the feature request!

**Is your feature request related to a problem? Please describe.**

I would like to set up all-contributors on a new project, and I want to acknowledge a bunch of existing contributors right away in a single comment.

**Describe the solution you'd like**

I'd like to be able to type a comment like this:

```
@all-contributors please add @hermione for ideas and code, @ron for questions, and @harry for docs and tooling.
```

**Describe alternatives you've considered**

I could just type multiple individual comments:

```
@all-contributors please add @hermione for ideas and code
@all-contributors please add @ron for questions
@all-contributors please add @harry for docs and tooling
```

.. but I'm afraid that could lead to multiple PRs with merge conflicts?

**Additional context**

I haven't tried any of this out yet, but took at look at the tests in https://github.com/all-contributors/all-contributors-bot/blob/69adf07f4625be6917887e56313fd34288b35591/test/tasks/processIssueComment/utils/parse-comment/index.test.js and didn't see any existing tests for these kinds of strings.

**Comment by js-kyle** [comment]
I agree, it would be helpful! It's a WIP over in https://github.com/all-contributors/all-contributors-bot/pull/127

**Comment by kkrieger85** [comment]
+1 for this request

**Comment by tenshiAMD** [comment]
PR https://github.com/all-contributors/app/pull/127 is almost done. Closing this one for now.
