### ISSUE TITLE
Bot is still looping to try to add contributions if it doesn't manage the first time

### ISSUE THREAD

**Issue by smoia** [all-contributors/app#295]
**Describe the bug**
Have a look at [this PR](https://github.com/physiopy/phys2bids/pull/134).
I invoked the all-contributors-bot to add a contribution (I deleted the message to prevent the bot from keeping commenting), and it started dumping comments in a loop.

Maybe this behaviour could be limited to one or two trials?

**To Reproduce**
1. Ask to add a contribution - possibly with an error or something that the bot doesn't recognise.
2. Wait until it starts looping.

**Comment by smoia** [comment]
It would also help if the error was more transparent (to know how to fix it).

**Comment by smoia** [comment]
This is related to all-contributors/all-contributors#362

**Comment by tenshiAMD** [comment]
@smoia is this still relevant today? Have you checked this using the latest version? Please check and let us know if this still occurs. Closing this for now. Thanks! 🎉
