### ISSUE TITLE
Add all commits before pushing

### ISSUE THREAD

**Issue by ouuan** [all-contributors/app#309]
**Is your feature request related to a problem? Please describe.**

Now the bot commits and pushes one by one, and this causes many CI runs (especially when you have multiple files with the contributor list).

You may think I can use the "skip CI" feature, but I'm using the branch protection rules and it requires CI passing for merging.

**Describe the solution you'd like**

Add all commits (i.e. modify the rc file, change all documents in the "files" array) before pushing.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by ouuan** [comment]
I just found [this action](https://github.com/rokroskar/workflow-run-cleanup-action). However, it will be better to add all commits before pushing, instead of requiring the CI to support automatic cancellation.

**Comment by ouuan** [comment]
Any thoughts on this?

**Comment by ouuan** [comment]
It seems that the current implementation uses GitHub API to update the files instead of committing and pushing at local. Maybe this feature request requires a huge refactoring :thinking:

**Comment by gr2m** [comment]
It is possible to combine multiple file changes into one file. 

Can you share an example where it happened? I'm not exactly sure what you mean with one-by-one?

**Comment by ouuan** [comment]
> Can you share an example where it happened?

https://github.com/cpeditor/cpeditor/pull/864

**Comment by gr2m** [comment]
I see, you mean you'd prefer to have a single commit that updates all files at once instead of having separate commits for all the file updates?

**Comment by ouuan** [comment]
> I see, you mean you'd prefer to have a single commit that updates all files at once instead of having separate commits for all the file updates?

That's a possible solution. What I want is a single push, which triggers a single CI run.

Supposing it's done in the terminal, I want:

```bash
git commit
git commit
git push
```

instead of:

```bash
git commit
git push
git commit
git push
```

**Comment by gr2m** [comment]
We don't do `git` commands, we use GItHub's APIs, and it doesn't permit to create multiple commits in a single request.

For the time being, you can use the concurrent setting for your GitHub Action workflows:
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency

You can set it that a workflow should only run once for the same pull request, and cancel a run if it was superceeded by a new commit.

**Comment by tenshiAMD** [comment]
@ouuan I think you can use [CLI](https://github.com/all-contributors/cli) instead for you use case. Closing this for now.
