### ISSUE TITLE
Bot has "trouble processing the request"

### ISSUE THREAD

**Issue by KirstieJane** [all-contributors/app#315]
**Describe the bug**

All contributors bot has trouble processing the request to add a new contributor.

See, for example: https://github.com/alan-turing-institute/the-turing-way/pull/822#issuecomment-584247891

**To Reproduce**

I typed the following in a pull request comment.

> Hey @allcontributors bot - please add @ACFaul for event organizing.

The bot replied saying:

> We had trouble processing your request. Please try again later.

We've had this problem for a few months unfortunately 😢 

**Expected behavior**
I was expecting the bot to open a new pull request 😬 

**Screenshots**

![image](https://user-images.githubusercontent.com/3626306/74176892-831bcd80-4c30-11ea-8eef-a00f2453be3d.png)

**Additional context**

This used to work, and I'm not sure what happened. It *might* be because I sometimes move the order around in the json file...but I don't think that's the case.

Thank you so much for your help!

**Comment by CSRedRat** [comment]
I have some trouble: https://github.com/CSRedRat/topalias/pull/4
will try without .allcontributorsrc and with .allcontributorsrc

**Comment by CSRedRat** [comment]
With cli all work fine, but bot not work: https://github.com/CSRedRat/topalias/issues/5

**Comment by outofambit** [comment]
We're seeing this issue over in https://github.com/processing/p5.js/issues/5268, has anyone found a workaround that isn't using the CLI?

**Comment by gr2m** [comment]
@outofambit glad it’s back to normal! It seems that GitHub API is experiencing some trouble, I see lots of time outs right now myself. Feel free to ping me directly next time :) Clio to see p5.js using @all-contributors

**Comment by brandonlenz** [comment]
This hasn't worked the last few times of infrequent attempts over the course of a month or so, e.g. https://github.com/trussworks/react-uswds/pull/2618#issuecomment-1768572938

Any way to debug the actual issue? If there were a problem with the repo config or a user, I would want the bot to indicate that. As of now, it just sounds like that underlying API is failing. Any way to check the status of things?

**Comment by gr2m** [comment]
> Any way to check the status of things separately from github status?

Unfortunately no, I can share access to the logs as they might include non-public data

**Comment by gr2m** [comment]
I do love the idea of having a view to self-debug problems, but it would require quite some work. We would need an OAuth flow to verify you have access to a given repository, and then show the logs in a custom UI. I'd be happy to provide guidance if anyone wants to build this, but cannot work on it myself
