### ISSUE TITLE
Stop processing when someone else is mentioned in a new paragraph

### ISSUE THREAD

**Issue by koppor** [all-contributors/app#317]
**Describe the bug**

I made following comment (see https://github.com/JabRef/abbrv.jabref.org/pull/67#issuecomment-683124304)

```markdown
@all-contributors please add @jlaehne for doc

(@jlaehne I am testing https://allcontributors.org/, hope that's OK)
```

The bot added `test` too:

```json
  "contributors": [
    {
      "login": "jlaehne",
      "name": "Jonas Lähnemann",
      "avatar_url": "https://avatars1.githubusercontent.com/u/7076057?v=4",
      "profile": "https://github.com/jlaehne",
      "contributions": [
        "doc",
        "test"
      ]
    }
  ],
```

**Expected behavior**

Bot should add `doc` only.

**Comment by tenshiAMD** [comment]
@koppor is this still relevant today? Have you checked this using the latest version? Please check and let us know if this still occurs. Closing this for now. Thanks! 🎉
