### ISSUE TITLE
bot not recognizing mentoring contribution

### ISSUE THREAD

**Issue by omarcostahamido** [all-contributors/app#319]
**Describe the bug**
bot is not recognizing when I add someone as mentoring.
According to [this list](https://all-contributors.js.org/docs/emoji-key#table) it is one of the accepted types of contributions.

**To Reproduce**
comment `@all-contributors please add @USERNAME for mentoring`

**Expected behavior**
it should just work

**Comment by tenshiAMD** [comment]
@omarcostahamido I just tried it using the latest version and it works. Let us know if this still occurs. Thanks! 🎉
