### ISSUE TITLE
Bot doesn't recognize .all-contributorsrc "files" array

### ISSUE THREAD

**Issue by Golodhros** [all-contributors/app#322]
**Describe the bug**
Using a configuration file that specifies other file than the README.md (https://github.com/amundsen-io/amundsen/blob/master/.all-contributorsrc), the bot doesn't seem to understand it, creating yet another '.all-contributorsrc' file and adding the new contributor to the README.md file

**To Reproduce**
1. Go to 'https://github.com/amundsen-io/amundsen/pull/733'
2. Suggest an addition, for example: `@all-contributors please add @Golodhros for bug`
3. Follow the link that will appear after some seconds to see the newly created PR
4. See that it is adding stuff into the README.md file, instead of into the CONTRIBUTORS.md file as requested on the .all-contributorsrc file

**Expected behavior**
Additions should go into the CONTRIBUTORS.md file, there shouldn't be a new .all-contributorsrc file

**Comment by tenshiAMD** [comment]
@Golodhros have you tried using the latest version? Let us know if this bug still occurs. Closing this for now. Thanks! 🎉
