### ISSUE TITLE
New line missing when adding "Contributions of any kind welcome!" paragraph to the end of README

### ISSUE THREAD

**Issue by gr2m** [all-contributors/app#340]
**Describe the bug**

My prettier linter complained that the `README.md` no longer complies after I merged the initial pull request of the All Contributors app. The app added the "Contributors" section. That change trimmed the new line from the end of the README:

**To Reproduce**

1. In a repository that does not have the app installed yet, and does not yet have the contributors section in the README, install the app
2. Ask the app to add someone as contributor
3. The resulting PR removes the new line from the README

**Expected behavior**

The `README.md` file changes should adhere to the prettier formatting rules

**Additional context**

Failing lint build:
https://github.com/probot/create-probot-app/runs/1690285771?check_suite_focus=true

**Comment by tenshiAMD** [comment]
@gr2m this issue does not occur anymore I've just tested this here https://github.com/tenshiAMD/sandbox-ac/pull/2/files. Closing this for now.
