### ISSUE TITLE
Not Updating the README 

### ISSUE THREAD

**Issue by akrish4** [all-contributors/app#341]
**Describe the bug**
I have copied the exact template given in docs and the bot is working fine when i write that command to add , but its not getting updated in readme , ls tell me what changes to be made in readme like how the table ? How to make it automatically add the table to readme ? 
**To Reproduce**

**Expected behavior**
I have copied the exact template given in docs and the bot is working fine when i write that command to add , but its not getting updated in readme , ls tell me what changes to be made in readme like how the table ? How to make it automatically add the table to readme ? 

**Screenshots**

**Additional context**

**Comment by Berkmann18** [comment]
I'm really not sure I understand what you wrote.
Is the bot creating a PR that edit the README (or whatever file set in `.all-contributorsrc`) and the config file?

**Comment by akrish4** [comment]
yes it is making pr , but it is not adding any users to readme 

i have just added the `.all-contributorsrc` file in root thtsall 
do i have to add a config file also ? where ? what is the filename and path?

One person told that I just have to add one comment in readme and then install bot and when i comment on any issue to add a user , the bot automatically creates a `.all-contributorsrc` for me ? is it ? 
Actually I have myself created the above file and copied the whole template given in docs 
Pls help

**Comment by gr2m** [comment]
Can you share one the URL of the PRs, even if the repo is private? We can look up in the logs if we find something out

**Comment by crimelabs786** [comment]
Hi, I've the same issue as @akrish4.

I'm sharing the details:

#### Sample PRs from bot that only updates the config file, not the README

-  https://github.com/indiainvestments/content/pull/34
- https://github.com/indiainvestments/content/pull/31

This was working quite well earlier, as you might have noticed from the closed PRs.

But then I changed repo visibility a few times (it was private in the beginning), and it started failing this way - empty commits for README changes.

**Comment by gr2m** [comment]
I think the problem might be that the two issues where you communicated with the bot are locked:

- https://github.com/indiainvestments/content/pull/31
- https://github.com/indiainvestments/content/issues/4#issuecomment-787396344

We receive according errors.

So what currently happens is: the process is not completed, an error is thrown.

I guess what should happen instead: ignore the "issue is locked" error and just continue.

Would you like to start creating a PR with a failing test, and we continue discussion there? The test would be added here:
https://github.com/all-contributors/app/blob/64fde8c89e845b26692bef353f9eaf8fc46cad45/test/integration/issue_comment.test.js. The response status to creating a comment in case the thread is locked is `403`, the response body is

```json
{
  "message": "Unable to create comment because issue is locked.",
  "documentation_url": "https://docs.github.com/articles/locking-conversations/"
}
```

The http mock in the new test would look like this

```js
      .post(
        "/repos/all-contributors/all-contributors-bot/issues/1/comments",
        (body) => {
          expect(body).toMatchSnapshot("request body");
          return true;
        }
      ).reply(403, {
        message: "Unable to create comment because issue is locked.",
        documentation_url: "https://docs.github.com/articles/locking-conversations/",
      });
```

**Comment by crimelabs786** [comment]
Hi @gr2m, thanks for promptly looking into it.

I locked that thread because of potential comment astro-turfing (I run a finance-related community on Reddit, let's just say GME saga has brought a lot of trolls out of the woodwork 😓 ).

Anyway, I unlocked the thread, created another contribution entry just now invoking the bot: https://github.com/indiainvestments/content/pull/37

It's still the same - `README.md` not getting updated.

**Comment by gr2m** [comment]
I'll look into it once I catch up with work today. I think these are two issues that might or might not be related.

The PR has a commit to update the README, but it's empty for some reason.

**Comment by crimelabs786** [comment]
Hi @gr2m 👋 

Just checking since it's been over a week now. Is there something we can do to get this moving? Happy to help 😃

**Comment by gr2m** [comment]
sorry for the delay. I have the issue in my backlog, I'll get to it eventually

**Comment by tisonkun** [comment]
I have the same issue as

https://github.com/zz-jason/tidb-dev-guide/commit/49b54134372465e555c31766b138b7bce1e8b514

**Comment by LovelyBuggies** [comment]
> I'm really not sure I understand what you wrote. Is the bot creating a PR that edit the README (or whatever file set in `.all-contributorsrc`) and the config file?

It's because you remove the comments of all-contributors.

**Comment by tenshiAMD** [comment]
@akrish4 is this still relevant today? Please let us know. Closing this one for now.
