### ISSUE TITLE
Don’t create PR when contributor is already exist

### ISSUE THREAD

**Issue by rluvaton** [all-contributors/app#345]
**Is your feature request related to a problem? Please describe.**
When a contribution been made by returning contributor and we ask a bot to add the contributor to the list it create an empty PR.

**Describe the solution you'd like**
What if when the bot is been asked to add a contributor it will check if the contributor is missing and only then it will add him, otherwise, it will replay with custom replay message or the default one “The user with this contribution type is already exist”

**Flow:**
![Flow](https://user-images.githubusercontent.com/16746759/109873024-dfa3bd80-7c75-11eb-9210-515be887b8d6.png)

**Comment by gr2m** [comment]
Thanks for opening the issue, I thought the app already did that today? Would you like to implement this?

**Comment by rluvaton** [comment]
> Thanks for opening the issue, 

Thank you for the quick replay!

> I thought the app already did that today?

I though that too but https://github.com/goldbergyoni/nodebestpractices/pull/903 is an example of creating a PR to add me as contributor when I already am.

> Would you like to implement this?

I'll try to find some time

**Comment by rluvaton** [comment]
@gr2m done - #346  😄
