### ISSUE TITLE
bot is not listening to issue body

### ISSUE THREAD

**Issue by 12rambau** [all-contributors/app#352]
**Describe the bug**
In this repository : https://github.com/openforis/sepal-doc
I've set up everything to update automatically the AUTHORS.rst file. 
But when i' wanted to test it with the following issue, the bot never answered (https://github.com/openforis/sepal-doc/issues/6)

**Expected behavior**
I would have expect to have at least an answer from the bot but nothing

**Comment by Berkmann18** [comment]
That's possibly because your config is missing fields. Have you created the config and generated the table yourself? Or with the CLI?

**Comment by 12rambau** [comment]
I've created the table myself previously and discovered the bot afterward. The config is reflecting the way i've designed it

**Comment by Berkmann18** [comment]
I see, have you tried using the CLI and saw if there were any issues?

**Comment by 12rambau** [comment]
I don't really know how to manage nodes dependencies and based on your doc the bot has been designed to avoid using the cli. 

My `.all-contributorsrc` file contains the following : 
```
{
  "files": ["AUTHORS.rst"],
  "imageSize": 100,
  "contributorsPerLine": 7,
  "contributorsSortAlphabetically": false,
  "badgeTemplate": "<img src="https://img.shields.io/badge/all_contributors-<%= contributors.length %>-orange.svg?style=flat-square" alt="All contributors">",
  "contributorTemplate": <a href=\"<%= contributor.profile %>\"><img src=\"<%= contributor.avatar_url %>\" width=\"<%= options.imageSize %>px;\" alt=\"\"/><br /><sub><b><%= contributor.name %></b></sub></a>",
  "skipCi": "true",
  "contributors": []
}
```

But from what I understand if a bug occurs during the handling of my request, the bot should anwser something like "I didn't understand your request".

**Comment by 12rambau** [comment]
Ok tested on my own repositories. So this is it, the bot is not answering if the app is only authorized on specific repository. Can it be considered a bug or is it a normal behaviour ?

**Comment by gr2m** [comment]
It should work if you install the app on selected repositories only, we don't use any organization/user account APIs. And I don't see any errors in our logs for your repository.

The problem with https://github.com/openforis/sepal-doc/issues/6 is that the bot does only listen to comments, not issue bodies. You are the 2nd person I see being confused by it, I think we should implement reacting to newly created issues, too.

Would you like to send a pull request for that?

**Comment by 12rambau** [comment]
If you can show me where to look I would be happy to open a PR

**Comment by krzkaczor** [comment]
@12rambau i've also run into problems with the bot in the past. In the end, I've created a GitHub Action that works much better IMO and even commits changes automatically to the repo: https://github.com/actionwareio/all-contributors-action

**Comment by 12rambau** [comment]
@krzkaczor I've already seen you advertising the gihub action process that you developed. It seems fantastic. 

BUT I don't want to authorize an automatic process to push to my repositories. I'm working with people that are not 100% reliable when it come to git processes so having the extra security of the PR is perfect to handle it. 

@gr2m I'm starting a fork. I've never used any of the technology used here, so if you aggree on helping me I can sure help.
"happy path" is part of 4 tests do I keep them all ? 

How can I know the structure of the response ?

**Comment by tenshiAMD** [comment]
@12rambau is this still irrelevant today? Closing this one for now.

**Comment by 12rambau** [comment]
I think it's not an issue any more, sorry for leaving it on stale

**Comment by tenshiAMD** [comment]
> I think it's not an issue any more, sorry for leaving it on stale

@12rambau it's okay. no worries 🎉
