### ISSUE TITLE
Listen to `push` event to default branch

### ISSUE THREAD

**Issue by oscard0m** [all-contributors/app#358]
### **Is your feature request related to a problem? Please describe.**
It would be nice if this GitHub App manages automatically merged PR's so a maintainer does not have to remember if a contributor was already in added and if not, to invoke the bot.

idea originally posted here: https://github.com/kentcdodds/react-fundamentals/pull/183#issuecomment-848072149

### **Describe the solution you'd like**
GitHub App listens to `push` event and if it is default branch, to add contributor\s of the PR accordingly without any maintainer manual invokation.

I have some doubts on how to manage the type/s of contributions automatically. To infer it from `semantic-commits` would be the best solution but it implies work I guess.

### **Describe alternatives you've considered**
I was considering a GitHub Action as an alternative option but I think is worth it to centralize everything. 

### **Additional context**
I'm open to discuss further into this if the community sees value into this and collaborate in the proposal and initial draft PR.

**Comment by gr2m** [comment]
> GitHub App listens to `push` event and if it is default branch, to add contributor\s of the PR accordingly without any maintainer manual invokation.
> 
> I have some doubts on how to manage the type/s of contributions automatically. To infer it from `semantic-commits` would be the best solution but it implies work I guess.

I don't think this is a good idea.

However, what we could do is an automation that will prompt the maintainers to add a new contributor if they haven't contributed in the past?

And even better: I think we should keep track of how often a contributor was thank for each contribution, even if we don't expose it. For larger projects, it makes sense to shorten the contributors table eventually, and we could make it based on the time of the last contribution by a user.

**Comment by oscard0m** [comment]
> > GitHub App listens to `push` event and if it is default branch, to add contributor\s of the PR accordingly without any maintainer manual invokation.
> 
> > 
> 
> > I have some doubts on how to manage the type/s of contributions automatically. To infer it from `semantic-commits` would be the best solution but it implies work I guess.
> 
> 
> 
> I don't think this is a good idea.
> 
> 
> 
> However, what we could do is an automation that will prompt the maintainers to add a new contributor if they haven't contributed in the past?
> 

I think this could be an easy solution for the problem of manually invoking the bot when you don't remember if the user was already added or not to the contributors list (and for that contribution type)

> 
> And even better: I think we should keep track of how often a contributor was thank for each contribution, even if we don't expose it. For larger projects, it makes sense to shorten the contributors table eventually, and we could make it based on the time of the last contribution by a user.

This sounds interesting to me but I would say is a different issue to work on. In my mind it would be a kind of option for maintainers to choose how large do they want to display contributor's table.

If you think it has sense to open a new issue for this second discussion I can do it myself.

**Comment by gr2m** [comment]
> What are your concerns on my proposal? Are you thinking about some use cases I could be missing?

I have two concerns. For one, I do not believe that we can automatically determine the type of contribution.

My second and more important concern is that I think appreciation should not be automated. It should take a human to look at a contribution and decide whether or not to appreciate the contribution, and how. If it doesn't take any effort, what is it even worth?

**Comment by oscard0m** [comment]
> > What are your concerns on my proposal? Are you thinking about some use cases I could be missing?
> 
> I have two concerns. For one, I do not believe that we can automatically determine the type of contribution.
> 
> My second and more important concern is that I think appreciation should not be automated. It should take a human to look at a contribution and decide whether or not to appreciate the contribution, and how. If it doesn't take any effort, what is it even worth?

I totally get your point and it's nice you remind us (even we love automation) when we still need human heat when talking about human relationships.

I was thinking... maybe [GitHub Saved Replies](https://docs.github.com/en/enterprise-server@3.0/github/writing-on-github/working-with-saved-replies/creating-a-saved-reply) could work for users? (Not sure if you are already using them @kentcdodds ).

I checked if GitHub API offers an option to programmatically add _Saved Responses_ but it seems like it is not possible. A community member posted about it in [GitHub Community](https://github.community/t/updating-saved-replies-for-all-organisation-members/151442) but no answer for the moment.

---

After all this disussion:
- Closing this issue (we can keep discussing on it)
- Opened a new one to talk about `Table format`:
