### ISSUE TITLE
To prompt the maintainers to add a new contributor if they haven't contributed in the past

### ISSUE THREAD

**Issue by oscard0m** [all-contributors/app#359]
_Originally posted by @gr2m in https://github.com/all-contributors/app/issues/358#issuecomment-848304512_

**Comment by gr2m** [comment]
Maybe we could offer an option, but I wouldn't want to enable this by default. It might be akward because it sets the default that a user whose first pull request was merged should be added to the list of contributors, and it puts pressure on the maintainer to then add them, even if the contribution was not worthy based on the project's standard

**Comment by oscard0m** [comment]
> Maybe we could offer an option, but I wouldn't want to enable this by default. It might be akward because it sets the default that a user whose first pull request was merged should be added to the list of contributors, and it puts pressure on the maintainer to then add them, even if the contribution was not worthy based on the project's standard

Good point. An option disabled by default would make a difference to your use case @kentcdodds ?

**Comment by kentcdodds** [comment]
I wouldn't want a comment, but a label would be cool I think.

**Comment by oscard0m** [comment]
> I wouldn't want a comment, but a label would be cool I think.

Something like... <kbd>new contributor</kbd> or <kbd>new contribution $type</kbd> ?

**Comment by gr2m** [comment]
I think GitHub adds a badge to contributors already. It says either "contributor" 

<img width="961" alt="image" src="https://user-images.githubusercontent.com/39992/119708472-0a368a00-be11-11eb-9731-9f6a974824d9.png">

or first-time contributor

<img width="975" alt="image" src="https://user-images.githubusercontent.com/39992/119708550-20444a80-be11-11eb-89bd-ab5db835f73e.png">

**Comment by kentcdodds** [comment]
Very good point. I think I just need to look at that more carefully 😅

**Comment by oscard0m** [comment]
Closing the issue. I think that badge can help a lot with the daily usage of the bot.
