### ISSUE TITLE
Github organisation private repo

### ISSUE THREAD

**Issue by bfoong-equinix** [all-contributors/app#367]
**Describe the bug**
All contributors bot currently doesn't respond to PR comments within Github organisation's private repo.

**Screenshots**
![Screenshot 2021-09-08 at 5 49 07 PM](https://user-images.githubusercontent.com/85331145/132487876-3504cc20-ba7d-4577-bea1-1d14ef72a363.png)
![Screenshot 2021-09-08 at 5 48 51 PM](https://user-images.githubusercontent.com/85331145/132487885-27bddeb8-2dc9-40b5-8499-c75bc5551e63.png)

**Additional context**
I've checked with the SRE team of my organisation and they have approved the use of the application. Is the bot only limited to be used in non organisation repo?

**Comment by gr2m** [comment]
> Is the bot only limited to be used in non organisation repo?

Definitely not, it should work. Can you share the name of the repository or at least the organization? I can have a look?

**Comment by bfoong-equinix** [comment]
@gr2m It is a private repository, the name of the organisation is equinix-product https://github.com/equinix-product. Thanks a lot!

**Comment by gr2m** [comment]
It seems like the organization is using an IP Allow List that is blocking the all-contributors app:

> Although you appear to have the correct authorization credentials, the `equinix-product` organization has an IP allow list enabled, and 24.176.174.119 is not permitted to access this resource.

The all-contributors app is running on Vercel. It's not possible to know what IP requests come from when deployed to Vercel, see https://vercel.com/support/articles/how-to-allowlist-deployment-ip-address

Nothing we can do on our side so I'll close the issue, but please let me know if you have any further questions
