### ISSUE TITLE
Contribution already registered even if PR is not merged

### ISSUE THREAD

**Issue by brosaplanella** [all-contributors/app#370]
**Describe the bug**
If the bot is asked to add a contributor for a given contribution and the PR is not merged, when asked again to add that contribution the bot replies that the user has already contributed before to that aspect. Might it be because the bot is checking the existing contribution against an internal log rather than against `all-contributorssrc`?

**To Reproduce**

1. Ask the bot to add a contribution to a user.
2. Close the resulting PR without merging
3. Ask the bot again to add the contribution

**Expected behavior**
The bot should open a new PR for that contribution.

**Comment by orsou** [comment]
Any fixes or workarounds for this?

**Comment by tenshiAMD** [comment]
@brosaplanella is this still relevant today? FYI, you need to delete the PR branch first. Let us know if this still occurs. Closing this for now. Thanks!

**Comment by brosaplanella** [comment]
I will have to check it when we encounter it again. If it happens, I will post it here. Thanks!
