### ISSUE TITLE
@all-contributors is not working but @allcontributor is working

### ISSUE THREAD

**Issue by Waz0x** [all-contributors/app#382]
**Describe the bug**
The bug is that the user to mention is not good in every pages of the wiki.

**To Reproduce**
1. Follow the wiki instructions

**Expected behavior**
My expectations are not to have to look for the right user to mention.

**Screenshots**
![image](https://user-images.githubusercontent.com/72010287/134000118-a76dceda-cccb-4c8b-be22-7b489af08269.png)

**Comment by gr2m** [comment]
@all-contributors please add @aaltat for bug
