### ISSUE TITLE
Support adding all current members of a team 

### ISSUE THREAD

**Issue by yarikoptic** [all-contributors/app#392]
**Is your feature request related to a problem? Please describe.**

Inability to easily add more than a single person at a time.
There is a 3 year old WiP PR https://github.com/all-contributors/app/pull/127 to add multiple people at the same time.
In our use case (https://github.com/con/open-brain-consent/pull/124) ideally, to avoid listing individual members, I would have loved to just be able to add the entire team to contributors.

I have tried in https://github.com/con/open-brain-consent/pull/124#issuecomment-1084715063 but it "failed" since submitted a PR for an entire organization (@con) instead of members of a team (@con/portuguese): https://github.com/con/open-brain-consent/pull/126/files 

**Describe the solution you'd like**
Be able to say

```
hey @all-contributors please add @con/portuguese for translation
```

and have all members of https://github.com/orgs/con/teams/portuguese to be submitted in a single PR to be added to contributors

**Describe alternatives you've considered**

listing individual ones whenever #127 is implemented, but it is not yet.

now I will need to spend time listing everyone individually in separate comments

**Comment by tenshiAMD** [comment]
@yarikoptic have you tried using https://github.com/all-contributors/cli? then create a custom script to loop all you need to add. That's the alternative for now.

**Comment by tenshiAMD** [comment]
PR https://github.com/all-contributors/app/pull/127 is almost done. 

I suggest you can do the following:

1) use the CLI and create a custom to loop each 
2) use the Bot with separate lines each contributor

Closing this one for now.
