### ISSUE TITLE
`research` contribution key is not recognized 

### ISSUE THREAD

**Issue by aybehrouz** [all-contributors/app#399]
**Describe the bug**
Research contribution key is not recognized.

**Expected behavior**
research is a valid key: https://allcontributors.org/docs/en/emoji-key

**Screenshots**
![image](https://user-images.githubusercontent.com/75391306/163381098-cba41fcf-8cc0-4b3b-9790-3e93f4a1d35e.png)

**Comment by Berkmann18** [comment]
Good point; it's not in https://github.com/all-contributors/app/blob/master/lib/parse-comment.js, would you say it's the only keyword missing, or would there be any other related to research that would make it easier to type while the bot still recognises the comment is about the `research` contribution type?

**Comment by aybehrouz** [comment]
I think it's the only keyword missing and I think `research` itself is a good keyword.

By the way I think that would be great if you guys add some new contribution types for "social media management" and also "project promotion/advertisement".

**Comment by Berkmann18** [comment]
@tenshiAMD @gr2m What do you guys think?

**Comment by gr2m** [comment]
I think we can add `research` and another one to cover social media / advertisement, such as `promotion`?
