### ISSUE TITLE
contributorsSortAlphabetically doesn't sort alphabetically using bot

### ISSUE THREAD

**Issue by KirstieJane** [all-contributors/app#416]
**Describe the bug**
I've added  `"contributorsSortAlphabetically": true,` to my repo's [`.allcontributorsrc.json` file](https://github.com/alan-turing-institute/the-turing-way/blob/master/.all-contributorsrc#L9). After I added a new contributor the table stayed in the same order and added the new contributor to the end of the table 😕 

Here's a link to the table: https://github.com/alan-turing-institute/the-turing-way#contributors

**To Reproduce**
1. Create table of contributors - use the bot for a little while
2. Add `"contributorsSortAlphabetically": true,` to the .allcontributorsrc.json file
3. Ask the All Contributors Bot 🤖 to add a new contributor
4. Receive a pull request from the bot which adds the contributor to the json file and the rendered table, but which does not re-order the table or file.

**Expected behavior**
I was expecting the table in the README file to be sorted in alphabetical order - although I wasn't sure if it would be ordered by username, first name or last name...

**Additional context**
This feature was added in https://github.com/all-contributors/all-contributors-cli/pull/249 by @alexwlchan.

**Comment by tenshiAMD** [comment]
@KirstieJane h. is this still relevant today? can you try now? let us know if this still occurs today. Closing this for now.
