### ISSUE TITLE
Custom PR text

### ISSUE THREAD

**Issue by CodingAleCR** [all-contributors/app#417]
**Is your feature request related to a problem? Please describe.**
I'm integrating Bitrise with a Github repository and all contributors PRs always trigger CI flows because [of the way that they handle the triggers.](https://devcenter.bitrise.io/builds/triggering-builds/skipping-a-given-commit-or-pull-request/)

**Describe the solution you'd like**
I would like to avoid triggering CI when doing contributor PRs by adding a custom PR text to add at the bottom of the PRs generated by the bot. I'm thinking it could be configured into .all-contributorsrc in a similar way that templates for contributor are set in it.

**Describe alternatives you've considered**
I looked into the skip CI commit type but they don't support it.

**Comment by tenshiAMD** [comment]
@CodingAleCR can you give some examples of the PR text you need? so we can write some tests. Thanks!

**Comment by tenshiAMD** [comment]
Related to https://github.com/all-contributors/app/issues/418.

**Comment by CodingAleCR** [comment]
What I've been wanting to do is to avoid the PRs created by all-contributors to trigger CI builds, this can be accomplished in many devops providers (azure pipelines, githubactions, etc) by including either [skip ci] or [ci skip] in the commit message

**Comment by tenshiAMD** [comment]
> What I've been wanting to do is to avoid the PRs created by all-contributors to trigger CI builds, this can be accomplished in many devops providers (azure pipelines, githubactions, etc) by including either [skip ci] or [ci skip] in the commit message

@CodingAleCR Currently, I think that's what the `skipCi` config is for. You can check [this one](https://github.com/all-contributors/app/pull/234) and notice that CI does not run anymore. Have you tried the latest version?

**Comment by tenshiAMD** [comment]
@CodingAleCR ok I see the issue now 

Bitrise implementation of skipping CI is using the PR title and description https://devcenter.bitrise.io/en/builds/starting-builds/skipping-a-given-commit-or-pull-request.html#preventing-a-pull-request-from-triggering-a-build

Bitrise stated this one in the link above

> To skip a pull request include the `skip ci` pattern in the pull request’s title or description.

I think the solution is to only add `[skip ci]` in the PR description when `skipCi` config is set to `true`.

**Comment by CodingAleCR** [comment]
Thank you, this will make my life easier (and tbh cheaper) when working with Bitrise's CI. You rock!

**Comment by tenshiAMD** [comment]
> Thank you, this will make my life easier (and tbh cheaper) when working with Bitrise's CI. You rock!

@CodingAleCR you're welcome. It will be nice if you follow me to show your appreciation. Thanks! 🎉

**Comment by tenshiAMD** [comment]
@all-contributors please add @CodingAleCR for bug

**Comment by tenshiAMD** [comment]
> Thank you, this will make my life easier (and tbh cheaper) when working with Bitrise's CI. You rock!

@CodingAleCR you're welcome. It will be nice if you follow me to show your appreciation. Thanks! 🎉
