### ISSUE TITLE
[Bug]: Contributors' link doesn't have correct url

### ISSUE THREAD

**Issue by Roshanjossey** [all-contributors/app#420]
**Describe the bug**
If you check https://github.com/all-contributors/all-contributors/blame/master/README.md#L200, you can see that the url in `href` attribute is missing the scheme ( `https://`). This would take users to wrong urls.
![image](https://user-images.githubusercontent.com/8488446/191613206-d9659bec-cb66-4e4e-94b1-8d45a9615274.png)

**Additional context**
It should be some formatting error where the bot fetches or drafts these links.

**Comment by tenshiAMD** [comment]
@Roshanjossey ok let me check and fix this one. Thanks for reporting.
