### ISSUE TITLE
Readme card not updating

### ISSUE THREAD

**Issue by weazzyefff** [all-contributors/app#446]
I have commited and pushed my new README file and it's updated when looking at the code. 

However, when you look at the card, it still has the old description. It's been over a week.

**To Reproduce**

1. Go to my profile
2. Check the repository - Rock-paper-scissors.
3. check the code of the README
4. Notice they're different. And it's been a week.

**Expected behavior**
Card updates.

**Screenshots**

![2022-11-22 22_01_08-](https://user-images.githubusercontent.com/64065022/203271668-c0947f26-0268-41e3-8b7e-31772f804d8d.png)

**Additional context**
None.

**Comment by tenshiAMD** [comment]
@weazzyefff Not sure what you mean here as I have checked the repo you mentioned above. I found no config file `.all-contributorsrc` so it will not work. Make sure you carefully follow the documentation. Closing this for now as this is an example of misconfiguration. Please let us know if you still having issues. Thank you.
