### ISSUE TITLE
Is there a way to remove contributors from a project?

### ISSUE THREAD

**Issue by zach-paper** [all-contributors/app#452]
Hi, I'd like to know if I can remove contributors from a project.

I added some test people for my project, but now I want to remove them and add the actual contributors. How can I do this?

**Comment by tenshiAMD** [comment]
> Hi, I'd like to know if I can remove contributors from a project.
> 
> I added some test people for my project, but now I want to remove them and add the actual contributors. How can I do this?

@zach-paper you can remove users in `.all-contributorsrc` file and then regenerate using the [CLI](https://github.com/all-contributors/app)

**Comment by tenshiAMD** [comment]
@zach-paper also it is unusual to remove a contributor in real-life use cases.  I think the best way is to manually remove (if really needed) by following my suggestion above. I think we can close this one for now.
