### ISSUE TITLE
Bot both creates a PR and complains about no contributions when extra text in comment

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [all-contributors/app#468]
## Describe the bug

With a(n accidentally) specially crafted comment, I've tricked the bot into both creating a PR and saying in the same comment that it couldn't determine any contributions:

> @JoshuaKGoldberg
> 
> I've put up [a pull request](https://github.com/JoshuaKGoldberg/template-typescript-node-package/pull/430) to add @JoshuaKGoldberg! 🎉
> 
> I couldn't determine any contributions to add, did you specify any contributions? Please make sure to use [valid contribution names](https://allcontributors.org/docs/en/emoji-key).

https://github.com/JoshuaKGoldberg/template-typescript-node-package/pull/429#issuecomment-1546457872

### To Reproduce

1. Set up allcontributors in a new repo
2. Post a comment with content after the `@all-contributors please add ...` line

### Expected behavior
The bot should ignore the extra content

## Additional context

I posted some more comments on that PR. It looks like the bug might have something to do with text like `all-contributors` existing?

**Comment by dannogr** [comment]
Hello man, great job!
