### ISSUE TITLE
"wE hAd TrOuBlE pRoCeSsInG yOuR rEqUeSt. PlEaSe TrY aGaIn LaTeR."

### ISSUE THREAD

**Issue by MichaelHinrichs** [all-contributors/app#486]
https://github.com/MichaelHinrichs/GitHub-Actions/pull/1

**Comment by nepalivai** [comment]
I have to bad title for people with OCD....... any way you don't have any contributors in the repo this occurred. It should rather be a feature request to check if there is no contributor telling "no contributor found"

**Comment by MichaelHinrichs** [comment]
Ok, first,
![alternating caps](https://github.com/all-contributors/app/assets/37460517/7b614baf-2eae-4b2b-a3eb-80ca58d089c5)
Second, i told all-contributors to add itself. It's already part of the project.

**Comment by MichaelHinrichs** [comment]
Bruh.

**Comment by MichaelHinrichs** [comment]
@nepalivai It just works now for no reason. Thaaaaaaaaaaaanks for the "Help".
